#!/bin/bash

set -eu

# remove header and footer
# remove html markup and blank lines
# convert italic tags to sq brackets
cat src/full.html \
| sed '21,8877!d' \
| sed 's/<\/i>/]/g' \
| sed 's/<i>/[/g' \
| sed 's/<[^>]*>//g' \
| bin/standardise-char-names.py \
| bin/normalise-whitespace.py 
